// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhcvyobkcmelxqzltjlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoY3Z5b2JrY21lbHhxemx0amx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTY3MTUsImV4cCI6MjA3MTQzMjcxNX0.Q92H4sms7JIbb48IhUbaRVm5uTuRv2d7-I2nA5kKHD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});